# Generated by Django 5.2.1 on 2025-06-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente5',
            new_name='Cliente',
        ),
    ]
